// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa.Infrastructure.Data;

#nullable disable

namespace Villa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa.Domain.Entities.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bhairuwa,AirPort,Nepal",
                            ImageUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/615097616.jpg?k=d3e34f137ebfb9de984a067006063753fb96a633cc96db9e5691f05df03e67d9&o=&hp=1",
                            Name = "Tiger palace",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kathmandu,Nepal",
                            ImageUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/615097642.jpg?k=dab2a4497b657504196a17c8cb8baaa08fec94ce43abe9dffa8795ac829b4913&o=&hp=1",
                            Name = "darbar Palace",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 3,
                            Description = "manigram,Butwal,Nepal",
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/73/41/a5/lobby-reception.jpg?w=700&h=-1&s=1",
                            Name = "Manigram Palace",
                            Occupancy = 5,
                            Price = 100.0,
                            Sqft = 400
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
